#!/bin/bash

set -eu

update_bashrc () {
  ln -snf "$HOME/.dotfiles/bash_profile" "$HOME/.bash_profile"
  ln -snf "$HOME/.dotfiles/bashrc" "$HOME/.bashrc"
  ln -snf "$HOME/.dotfiles/git-prompt-colors.sh" "$HOME/.git-prompt-colors.sh"
}

install_base16 () {
  mkdir -p "$HOME/.config"
  ln -snf "$HOME/.dotfiles/base16-shell" "$HOME/.config/base16-shell"
}

update_git () {
  read -p "Keep git user settings for Robbie Clarken (y/n)? " keep_git_user
  ln -sf "$HOME/.dotfiles/git/gitconfig" "$HOME/.gitconfig"
  if [[ "$keep_git_user" != "y" ]]; then
    git config --global --remove-section user
  fi
}

update_vimrc () {
  if [[ -e "$HOME/.vim" ]]; then
    rm -rf "$HOME/.vim"
  fi
  ln -snf "$HOME/.dotfiles/vim" "$HOME/.vim"
  ln -snf "$HOME/.vim/vimrc" "$HOME/.vimrc"
  if hash vim 2>/dev/null; then
    vim +PlugInstall +qall
  fi
}

update_tmux_conf () {
  ln -snf "$HOME/.dotfiles/tmux" "$HOME/.tmux"
  ln -snf "$HOME/.tmux/tmux.conf" "$HOME/.tmux.conf"
}

update_others () {
  ln -snf "$HOME/.dotfiles/ctags" "$HOME/.ctags"
  ln -snf "$HOME/.dotfiles/ignore" "$HOME/.rgignore"
  ln -snf "$HOME/.dotfiles/ignore" "$HOME/.fdignore"
}

main () {
  update_bashrc
  install_base16
  update_git
  update_vimrc
  update_tmux_conf
  update_others
}

main "$@"
